fix(Tests): Fix MapProfilingTest compilation error with ProfilingEntity
Fixed vector initialization error where ProfilingEntity has deleted copy
constructor but vector was trying to use copy-construction.

Changed from:
  std::vector<ProfilingEntity> objects(NUM_OBJECTS, ProfilingEntity(workloadIterations));

To:
  std::vector<ProfilingEntity> objects;
  objects.reserve(NUM_OBJECTS);
  for (size_t i = 0; i < NUM_OBJECTS; ++i)
      objects.emplace_back(workloadIterations);

This uses move semantics via emplace_back() instead of copy construction.

Error was:
  error: no matching function for call to 'construct_at'
  error: call to deleted constructor of 'ProfilingEntity'